version: '8.0'
services:
  db:
    image: mysql:8.0
    container_name: mysqlgs
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - globalsolution_data:/var/lib/mysql

volumes:
  globalsolution_data:
